version: "3.9"

name: ceov

services:

  mongo:
    image: mongo:6
    container_name: ceov-mongodb
    networks:
      - ceov-network
    ports:
      - "27017:27017"
    volumes:
      - ceov-mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: ceov-keycloak
    networks:
      - ceov-network
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
        - ceov-keycloak-data:/opt/keycloak/data     # ✅ persistência real
        - ./infra/keycloak:/opt/keycloak/data/import
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: assistencia-espiritual-backend
    networks:
      - ceov-network
    depends_on:
      mongo:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongo:27017
      QUARKUS_MONGODB_DATABASE: ceov

      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/ceov
      QUARKUS_OIDC_CLIENT_ID: backend
      QUARKUS_OIDC_APPLICATION_TYPE: service

    ports:
      - "8080:8080"
     
  
networks:
  ceov-network:
    name: ceov-network

volumes:
  ceov-mongo-data:
    name: ceov-mongo-data
  ceov-keycloak-data:
    name: ceov-keycloak-data    
